# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.2.dev0+g8672ea1.d20250731'
__version_tuple__ = version_tuple = (0, 1, 2, 'dev0', 'g8672ea1.d20250731')
